version: '3.2'

services:
  contracts:
    image: derreichi/contracts:latest
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - contracts

  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cgi
    networks:
      - contracts

  elasticsearch:
    image: elasticsearch:7.14.2
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - contracts

  kibana:
    image: kibana:7.14.2
    hostname: kibana
    ports:
      - 5601:5601
    environment:
      - discovery.type=single-node
    depends_on:
      - elasticsearch
    networks:
      - contracts


  zoo:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo:2888:3888
#    volumes:
#      - type: volume
#        source: zksingle-ksingle_zoo1-data
#        target: /data
#      - type: volume
#        source: zksingle-ksingle_zoo1-log
#        target: /datalog
    networks:
      - contracts

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    hostname: kafka
    user: "appuser:appuser"
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
#    volumes:
#      - type: volume
#        source: zksingle-ksingle_kafka1-data
#        target: /var/lib/kafka/data
    networks:
      - contracts
    depends_on:
      - zoo

networks:
  contracts:
    driver: bridge
